### try-catch
```kotlin
fun main(): Unit = runBlocking {
	1. val job = launch {
	2. 	try {
	3. 		delay(1_000L)
	  	} catch (e: CancellationException) {
	4. 		// 예외를 잡아서 먹어버린다.
	  	}

	5. 	printWithThread("delay에 의해 취소되지 않았다!")
	}

	6. delay(100L)
	7. printWithThread("취소 시작")
	8. job.cancel()
 }
// 취소 시작
// delay에 의해 취소되지 않았다!
```
실행순서
1 → 6 → 2 → 3 → 7 → 8 → 4 → 5

### finally
```kotlin
fun main(): Unit = runBlocking {
	1. val job = launch {
		 try {
	2.		delay(1_000L)
	  	} finally {
	3.		// 자원을 적절히 닫을 수 있다.
		  }
	
	4.  printWithThread("delay에 의해 취소되지 않았다!")
	  }

	5. delay(100L)
	6. printWithThread("취소 시작")
	7. job.cancel()
 }
// 취소 시작
```
실행순서
1 → 5 → 2 → 6 → 7 → 3